server:
  port: 9595

spring:
  data:
    mongodb:
      host: 0.0.0.0
      port: 27017
      database: admin
      username: mongoadmin
      password: example
      repositories:
        type: auto
